#include"track.h"

int main()
{

    // Local iconic variables
    HObject  ho_Image_n1, ho_Image_n, ho_RegionDynThresh;
    HObject  ho_RegionOpening, ho_RegionClosing, ho_ConnectedRegions;
    HObject  ho_SelectedRegions, ho_RegionTrans, ho_Img_n_1;

    // Local control variables
    HTuple  hv_Thresh, hv_AcqHandle, hv_WindowHandle;

    hv_Thresh = 35;

    if (HDevWindowStack::IsOpen())
        SetDraw(HDevWindowStack::GetActive(), "margin");
    if (HDevWindowStack::IsOpen())
        SetColored(HDevWindowStack::GetActive(), 12);
    if (HDevWindowStack::IsOpen())
        SetLineWidth(HDevWindowStack::GetActive(), 3);
    if (HDevWindowStack::IsOpen())
        CloseWindow(HDevWindowStack::Pop());

    //Image Acquisition 02: Code generated by Image Acquisition 02
    OpenFramegrabber("DirectShow", 1, 1, 0, 0, 0, 0, "default", 8, "rgb", -1, "false",
        "default", "[1] Integrated Camera", 0, -1, &hv_AcqHandle);

    //open_framegrabber ('DirectShow', 1, 1, 0, 0, 0, 0, 'default', 8, 'gray', -1, 'false', 'default', '[0] YW500', 0, -1, AcqHandle)
    GrabImageStart(hv_AcqHandle, -1);
    GrabImageAsync(&ho_Image_n1, hv_AcqHandle, -1);

    dev_open_window_fit_image(ho_Image_n1, 0, 0, -1, -1, &hv_WindowHandle);


    while (true)
    {
        GrabImageAsync(&ho_Image_n, hv_AcqHandle, -1);
        DynThreshold(ho_Image_n1, ho_Image_n, &ho_RegionDynThresh, hv_Thresh, "not_equal");
        OpeningCircle(ho_RegionDynThresh, &ho_RegionOpening, 2.5);
        ClosingCircle(ho_RegionDynThresh, &ho_RegionClosing, 3.5);
        Connection(ho_RegionClosing, &ho_ConnectedRegions);
        SelectShape(ho_ConnectedRegions, &ho_SelectedRegions, "area", "or", 200, 10000);
        ShapeTrans(ho_SelectedRegions, &ho_RegionTrans, "convex");
        if (HDevWindowStack::IsOpen())
            DispObj(ho_Image_n, HDevWindowStack::GetActive());
        if (HDevWindowStack::IsOpen())
            DispObj(ho_RegionTrans, HDevWindowStack::GetActive());
        SelectObj(ho_Image_n, &ho_Img_n_1, 1);
        WaitSeconds(0.02);
    }
    CloseFramegrabber(hv_AcqHandle);

}